# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir /media/huutan86/Data/source_code/ECE527/mps/mp1/partB/part_B.cache/wt [current_project]
set_property parent.project_path /media/huutan86/Data/source_code/ECE527/mps/mp1/partB/part_B.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
read_verilog -library xil_defaultlib /media/huutan86/Data/source_code/ECE527/mps/mp1/partB/part_B.srcs/sources_1/new/part_B.v
read_xdc /media/huutan86/Data/source_code/ECE527/mps/mp1/partB/part_B.srcs/constrs_1/new/partB_constr.xdc
set_property used_in_implementation false [get_files /media/huutan86/Data/source_code/ECE527/mps/mp1/partB/part_B.srcs/constrs_1/new/partB_constr.xdc]

synth_design -top part_B -part xc7z020clg484-1
write_checkpoint -noxdef part_B.dcp
catch { report_utilization -file part_B_utilization_synth.rpt -pb part_B_utilization_synth.pb }
