#pragma line 1 "dct/matrixmath.c" ::: -10
#pragma line 1 "dct/matrixmath.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 279 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 7 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "dct/matrixmath.c" 2 ::: 183
#pragma line 1 "dct/matrixmath.h" 1 ::: 185
#pragma line 3 "dct/matrixmath.c" 2 ::: 204
#pragma line 6 "dct/matrixmath.c" ::: 210
#pragma line 6 "dct/matrixmath.c" ::: 213
#pragma line 9 "dct/matrixmath.c" ::: 219
#pragma line 12 "dct/matrixmath.c" ::: 225
#pragma line 19 "dct/matrixmath.c" ::: 235
#pragma line 33 "dct/matrixmath.c" ::: 252
#pragma line 33 "dct/matrixmath.c" ::: 255
#pragma line 36 "dct/matrixmath.c" ::: 261
#pragma line 41 "dct/matrixmath.c" ::: 269
#pragma line 44 "dct/matrixmath.c" ::: 275
