lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "A"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "B"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "A_cached_row"}
lappend pragmaStatus3 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "DCT" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DCT' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply/Col" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus7 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply2/Col" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "B_cached"}
lappend pragmaStatus9 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply2/RowCaching" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/matrixmath.c" location "MAT_Multiply/LoadCol" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file." variable "A"}
lappend pragmaStatus1 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus2 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file." variable "A_cached_row"}
lappend pragmaStatus3 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "DCT" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus5 {pragma "DATAFLOW" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus7 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply2/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file." variable "B_cached"}
lappend pragmaStatus9 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply2/RowCaching" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "PIPELINE" source "E:/Ubuntu_source_code_data/ECE_527_MP/mp4/dct/dct.c" location "MAT_Multiply/LoadCol" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
