#pragma line 1 "dct/quant.c" ::: -10
#pragma line 1 "dct/quant.c" 1 ::: -9
#pragma line 1 "<built-in>" 1 ::: -8
#pragma line 1 "<built-in>" 3 ::: -7
#pragma line 147 "<built-in>" 3 ::: -6
#pragma line 1 "<command line>" 1 ::: -5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 1
#pragma line 279 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 54
#pragma line 7 "<command line>" 2 ::: 181
#pragma line 1 "<built-in>" 2 ::: 182
#pragma line 1 "dct/quant.c" 2 ::: 183
#pragma line 1 "dct/quant.h" 1 ::: 185
#pragma line 1 "dct/matrixmath.h" 1 ::: 190
#pragma line 5 "dct/quant.h" 2 ::: 209
#pragma line 2 "dct/quant.c" 2 ::: 219
