#! /bin/sh
set -e

if [ "$1" = "configure" ] ; then
  # gnome-games scores files get root:games
  SCORE_FILES="gnomine.Custom.scores gnomine.Large.scores gnomine.Medium.scores gnomine.Small.scores"

  if [ ! -d /var/games ]; then
	mkdir /var/games
  fi

  for FILES in $SCORE_FILES; do
	if [ -e /var/games/$FILES ]; then
		continue
	fi

	touch /var/games/$FILES
	chown root:games /var/games/$FILES
	chmod 664 /var/games/$FILES
  done
fi


