#! /bin/sh
set -e

if [ "$1" = "purge" ] ; then
  # remove empty/unused scorefiles
  SCORE_FILES="mahjongg.bridges.scores mahjongg.cloud.scores mahjongg.confounding.scores mahjongg.difficult.scores mahjongg.dragon.scores mahjongg.easy.scores mahjongg.pyramid.scores mahjongg.tictactoe.scores mahjongg.ziggurat.scores"

  for FILE in $SCORE_FILES; do
	rm -f /var/games/$FILE
  done

  if [ -d /var/games ]; then
	rmdir --ignore-fail-on-non-empty /var/games
  fi
fi


