#!/bin/sh
set -e
# Automatically added by dh_icons
if which update-icon-caches >/dev/null 2>&1 ; then
	update-icon-caches /usr/share/icons/ubuntu-mono-dark /usr/share/icons/ubuntu-mono-light
fi
# End automatically added section

# Automatically added by dh_python2:
if which pycompile >/dev/null 2>&1; then
	pycompile -p onboard 
fi

if which pycompile >/dev/null 2>&1; then
	pycompile -p onboard /usr/share/onboard -V 2.7-
fi

# End automatically added section
