#pragma line 1 "accelerator/dct.c" ::: 0
#pragma line 1 "accelerator/dct.c" 1 ::: 1
#pragma line 1 "<built-in>" 1 ::: 2
#pragma line 1 "<built-in>" 3 ::: 3
#pragma line 147 "<built-in>" 3 ::: 4
#pragma line 1 "<command line>" 1 ::: 5
#pragma line 1 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" 1 ::: 11
#pragma line 279 "C:/Xilinx/Vivado_HLS/2015.1/common/technology/autopilot\\etc/autopilot_ssdm_op.h" ::: 64
#pragma line 7 "<command line>" 2 ::: 191
#pragma line 1 "<built-in>" 2 ::: 192
#pragma line 1 "accelerator/dct.c" 2 ::: 193
#pragma line 1 "accelerator/dct.h" 1 ::: 195
#pragma line 1 "accelerator/matrixmath.h" 1 ::: 200
#pragma line 6 "accelerator/dct.h" 2 ::: 220
#pragma line 3 "accelerator/dct.c" 2 ::: 229
#pragma line 1 "accelerator/coeff.h" 1 ::: 231
#pragma line 5 "accelerator/dct.c" 2 ::: 257
