lappend pragmaStatus0 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file." variable "A"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus7 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus9 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus11 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply/LoadRow" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply2/RowCaching" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "MAT_Multiply2/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Multiply/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DOT_Divide/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "DCT" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DCT' does not exist in any synthesis source file."}
lappend pragmaStatus18 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/quant.c" location "Quant" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus0 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "A"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply2" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "B"}
lappend pragmaStatus7 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Multiply" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "B"}
lappend pragmaStatus9 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Divide" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Divide" found 1 funcFound 1 applied 1 ambiguous 0 reason "null" variable "B"}
lappend pragmaStatus11 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply/LoadRow" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus12 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply/Col" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus13 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply2/RowCaching" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus14 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "MAT_Multiply2/Col" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus15 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Multiply/row" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus16 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DOT_Divide/row" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus17 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "DCT" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DCT' does not exist in any synthesis source file."}
lappend pragmaStatus18 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/matrixmath.c" location "Quant" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Quant' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus1 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'INTERFACE' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus2 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "Accelerator" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Accelerator' does not exist in any synthesis source file."}
lappend pragmaStatus3 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file." variable "A"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus7 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus9 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus11 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply/LoadRow" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply2/RowCaching" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "MAT_Multiply2/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Multiply/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DOT_Divide/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "DCT" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus18 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/dct.c" location "Quant" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Quant' does not exist in any synthesis source file."}
lappend pragmaStatus0 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "Accelerator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus1 {pragma "INTERFACE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "Accelerator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus2 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "Accelerator" found 1 funcFound 1 applied 1 ambiguous 0 reason "null"}
lappend pragmaStatus3 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus4 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file." variable "A"}
lappend pragmaStatus5 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus6 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply2" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus7 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus8 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Multiply" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus9 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus10 {pragma "ARRAY_PARTITION" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Divide" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'ARRAY_PARTITION' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file." variable "B"}
lappend pragmaStatus11 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply/LoadRow" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus12 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus13 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply2/RowCaching" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus14 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "MAT_Multiply2/Col" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'MAT_Multiply2' does not exist in any synthesis source file."}
lappend pragmaStatus15 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Multiply/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Multiply' does not exist in any synthesis source file."}
lappend pragmaStatus16 {pragma "PIPELINE" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DOT_Divide/row" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'PIPELINE' cannot be applied: Function 'DOT_Divide' does not exist in any synthesis source file."}
lappend pragmaStatus17 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "DCT" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'DCT' does not exist in any synthesis source file."}
lappend pragmaStatus18 {pragma "DATAFLOW" source "Z:/Documents/UIUC/ECE527/ECE_527_MP/mp4/hls/accelerator/accelerator.c" location "Quant" found 0 funcFound 0 applied 0 ambiguous 0 reason "Directive 'DATAFLOW' cannot be applied: Function 'Quant' does not exist in any synthesis source file."}
