# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# Block Designs: bd/partB/partB.bd
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB || ORIG_REF_NAME==partB}]

# IP: bd/partB/ip/partB_processing_system7_0_0/partB_processing_system7_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_processing_system7_0_0 || ORIG_REF_NAME==partB_processing_system7_0_0}]

# IP: bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_axi_dma_0_0 || ORIG_REF_NAME==partB_axi_dma_0_0}]

# IP: bd/partB/ip/partB_processing_system7_0_axi_periph_1/partB_processing_system7_0_axi_periph_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_processing_system7_0_axi_periph_1 || ORIG_REF_NAME==partB_processing_system7_0_axi_periph_1}]

# IP: bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==partB_rst_processing_system7_0_100M_0}]

# IP: bd/partB/ip/partB_axi_mem_intercon_0/partB_axi_mem_intercon_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_axi_mem_intercon_0 || ORIG_REF_NAME==partB_axi_mem_intercon_0}]

# IP: bd/partB/ip/partB_xbar_0/partB_xbar_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_xbar_0 || ORIG_REF_NAME==partB_xbar_0}]

# IP: bd/partB/ip/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_axis_data_fifo_0_0 || ORIG_REF_NAME==partB_axis_data_fifo_0_0}]

# IP: bd/partB/ip/partB_xlconcat_0_0/partB_xlconcat_0_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_xlconcat_0_0 || ORIG_REF_NAME==partB_xlconcat_0_0}]

# IP: bd/partB/ip/partB_auto_pc_0/partB_auto_pc_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_auto_pc_0 || ORIG_REF_NAME==partB_auto_pc_0}]

# IP: bd/partB/ip/partB_auto_pc_1/partB_auto_pc_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_auto_pc_1 || ORIG_REF_NAME==partB_auto_pc_1}]

# IP: bd/partB/ip/partB_auto_us_0/partB_auto_us_0.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_auto_us_0 || ORIG_REF_NAME==partB_auto_us_0}]

# IP: bd/partB/ip/partB_auto_us_1/partB_auto_us_1.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_auto_us_1 || ORIG_REF_NAME==partB_auto_us_1}]

# IP: bd/partB/ip/partB_auto_us_2/partB_auto_us_2.xci
set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_auto_us_2 || ORIG_REF_NAME==partB_auto_us_2}]

# XDC: bd/partB/ip/partB_processing_system7_0_0/partB_processing_system7_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_processing_system7_0_0 || ORIG_REF_NAME==partB_processing_system7_0_0}] {/inst }]/inst ]]

# XDC: bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0_ooc.xdc

# XDC: bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_axi_dma_0_0 || ORIG_REF_NAME==partB_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0_clocks.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_axi_dma_0_0 || ORIG_REF_NAME==partB_axi_dma_0_0}] {/U0 }]/U0 ]]

# XDC: bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0_board.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==partB_rst_processing_system7_0_100M_0}]

# XDC: bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0.xdc
#dup# set_property DONT_TOUCH TRUE [get_cells -hier -filter {REF_NAME==partB_rst_processing_system7_0_100M_0 || ORIG_REF_NAME==partB_rst_processing_system7_0_100M_0}]

# XDC: bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0_ooc.xdc

# XDC: bd/partB/ip/partB_xbar_0/partB_xbar_0_ooc.xdc

# XDC: bd/partB/ip/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0_ooc.xdc

# XDC: bd/partB/ip/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_axis_data_fifo_0_0 || ORIG_REF_NAME==partB_axis_data_fifo_0_0}] {/inst }]/inst ]]

# XDC: bd/partB/ip/partB_auto_pc_0/partB_auto_pc_0_ooc.xdc

# XDC: bd/partB/ip/partB_auto_pc_1/partB_auto_pc_1_ooc.xdc

# XDC: bd/partB/ip/partB_auto_us_0/partB_auto_us_0_ooc.xdc

# XDC: bd/partB/ip/partB_auto_us_0/partB_auto_us_0_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_auto_us_0 || ORIG_REF_NAME==partB_auto_us_0}] {/inst }]/inst ]]

# XDC: bd/partB/ip/partB_auto_us_1/partB_auto_us_1_ooc.xdc

# XDC: bd/partB/ip/partB_auto_us_1/partB_auto_us_1_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_auto_us_1 || ORIG_REF_NAME==partB_auto_us_1}] {/inst }]/inst ]]

# XDC: bd/partB/ip/partB_auto_us_2/partB_auto_us_2_ooc.xdc

# XDC: bd/partB/ip/partB_auto_us_2/partB_auto_us_2_clocks.xdc
set_property DONT_TOUCH TRUE [get_cells [split [join [get_cells -hier -filter {REF_NAME==partB_auto_us_2 || ORIG_REF_NAME==partB_auto_us_2}] {/inst }]/inst ]]

# XDC: bd/partB/partB_ooc.xdc
