<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN"><html><head>
<html> 
<head> 
        <title>my LaTeX pages</title>
</head>
<body bgcolor="#ffffff" text="#000000" link="#aa0000" alink="#ff3300" vlink="#330099">
	<hr noshade="noshade">
	<h1>pst-geo by Manuel Luque, Giuseppe Mattarazzi, Herbert Voﬂ</h1>
<h4> All the files have a <strong>Beta-Status</strong>! For a stable version look at <a href="ftp://ftp.dante
.de/pub/tex/graphics/pstricks/contrib/pst-3dplot/">CTAN</a></h4>
	<hr noshade="noshade">
	<div class=text> 
<? 
$cdir = dir("./"); 

$entries=array();
while ($entry = $cdir->read()) 
	$entries[] = $entry;

echo "Files in this directory:"; 
echo "	<hr noshade=\"noshade\">"; 
echo "<table>";

asort($entries);
reset($entries);

//foreach($entries as $entry) {
while (list(, $entry) = each($entries)) {
//   if (!is_dir($entry) && ($entry != "index.phtml") && ($entry != ".htaccess")) {
   if (($entry != ".") && ($entry != "index.phtml") && ($entry != ".htaccess")) {
    echo "<tr>";
      echo "<td><a href=\"$entry\">$entry</a></td>"; 
      if (is_dir($entry))
        echo "<td>&lt;Dir&gt;</td>";
      else
        echo "<td></td>";
      echo "<td align=\"right\">&nbsp;".filesize($entry)." Byte&nbsp;</td>"; 
      echo "<td align=\"right\">&nbsp;".date("D, j F Y, H:i:s",filemtime($entry))."&nbsp;</td>"; 
      echo "</tr>";
   } 
}
echo "</table>";

?> 
<hr noshade="noshade">
Page last updated on <?php echo date("d.m.Y", getlastmod() ); ?>
</p>
</div> 
<hr>
<?
if (file_exists("README")) {
	$fp = fopen("README","r");
	echo "<pre>";
	while ($line=fgets($fp,1000)) {
		echo "$line";
	}
	echo "</pre>";
	fclose($fp);
}
?>
</body> 
</html>
