// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

(* CORE_GENERATION_INFO="MAT_Multiply,hls_ip_2015_1,{HLS_INPUT_TYPE=c,HLS_INPUT_FLOAT=0,HLS_INPUT_FIXED=0,HLS_INPUT_PART=xc7z020clg484-1,HLS_INPUT_CLOCK=10.000000,HLS_INPUT_ARCH=others,HLS_SYN_CLOCK=7.085000,HLS_SYN_LAT=256403,HLS_SYN_TPT=none,HLS_SYN_MEM=32,HLS_SYN_DSP=4,HLS_SYN_FF=426,HLS_SYN_LUT=655}" *)

module MAT_Multiply (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        A_dout,
        A_empty_n,
        A_read,
        B_dout,
        B_empty_n,
        B_read,
        C_din,
        C_full_n,
        C_write,
        mA,
        nA,
        mB,
        nB,
        mC,
        nC
);

parameter    ap_const_logic_1 = 1'b1;
parameter    ap_const_logic_0 = 1'b0;
parameter    ap_ST_st1_fsm_0 = 16'b1;
parameter    ap_ST_st2_fsm_1 = 16'b10;
parameter    ap_ST_st3_fsm_2 = 16'b100;
parameter    ap_ST_st4_fsm_3 = 16'b1000;
parameter    ap_ST_st5_fsm_4 = 16'b10000;
parameter    ap_ST_st6_fsm_5 = 16'b100000;
parameter    ap_ST_st7_fsm_6 = 16'b1000000;
parameter    ap_ST_st8_fsm_7 = 16'b10000000;
parameter    ap_ST_st9_fsm_8 = 16'b100000000;
parameter    ap_ST_st10_fsm_9 = 16'b1000000000;
parameter    ap_ST_st11_fsm_10 = 16'b10000000000;
parameter    ap_ST_st12_fsm_11 = 16'b100000000000;
parameter    ap_ST_st13_fsm_12 = 16'b1000000000000;
parameter    ap_ST_st14_fsm_13 = 16'b10000000000000;
parameter    ap_ST_st15_fsm_14 = 16'b100000000000000;
parameter    ap_ST_st16_fsm_15 = 16'b1000000000000000;
parameter    ap_const_lv32_0 = 32'b00000000000000000000000000000000;
parameter    ap_const_lv1_1 = 1'b1;
parameter    ap_const_lv32_2 = 32'b10;
parameter    ap_const_lv1_0 = 1'b0;
parameter    ap_const_lv32_3 = 32'b11;
parameter    ap_const_lv32_4 = 32'b100;
parameter    ap_const_lv32_5 = 32'b101;
parameter    ap_const_lv32_B = 32'b1011;
parameter    ap_const_lv32_D = 32'b1101;
parameter    ap_const_lv32_E = 32'b1110;
parameter    ap_const_lv6_0 = 6'b000000;
parameter    ap_const_lv32_1 = 32'b1;
parameter    ap_const_lv12_0 = 12'b000000000000;
parameter    ap_const_lv32_C = 32'b1100;
parameter    ap_const_lv32_F = 32'b1111;
parameter    ap_const_lv64_0 = 64'b0000000000000000000000000000000000000000000000000000000000000000;
parameter    ap_const_lv32_A = 32'b1010;
parameter    ap_const_lv12_32 = 12'b110010;
parameter    ap_const_lv6_32 = 6'b110010;
parameter    ap_const_lv6_1 = 6'b1;
parameter    ap_const_lv32_6 = 32'b110;
parameter    ap_true = 1'b1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [31:0] A_dout;
input   A_empty_n;
output   A_read;
input  [31:0] B_dout;
input   B_empty_n;
output   B_read;
output  [63:0] C_din;
input   C_full_n;
output   C_write;
input  [31:0] mA;
input  [31:0] nA;
input  [31:0] mB;
input  [31:0] nB;
input  [31:0] mC;
input  [31:0] nC;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg A_read;
reg B_read;
reg C_write;
(* fsm_encoding = "none" *) reg   [15:0] ap_CS_fsm = 16'b1;
reg    ap_sig_cseq_ST_st1_fsm_0;
reg    ap_sig_bdd_32;
wire   [0:0] tmp_s_fu_310_p2;
reg   [0:0] tmp_s_reg_538;
wire   [11:0] next_mul1_fu_316_p2;
reg   [11:0] next_mul1_reg_542;
reg    ap_sig_cseq_ST_st3_fsm_2;
reg    ap_sig_bdd_75;
wire   [5:0] i_2_fu_332_p2;
reg   [5:0] i_2_reg_550;
wire   [0:0] tmp_2_fu_338_p2;
reg   [0:0] tmp_2_reg_555;
wire   [0:0] exitcond4_fu_326_p2;
wire   [11:0] j_cast7_cast_fu_347_p1;
reg   [11:0] j_cast7_cast_reg_560;
reg    ap_sig_cseq_ST_st4_fsm_3;
reg    ap_sig_bdd_92;
wire   [5:0] j_2_fu_357_p2;
reg   [5:0] j_2_reg_568;
reg   [11:0] arrayC_addr_reg_573;
wire   [0:0] exitcond3_fu_351_p2;
wire   [0:0] tmp_10_fu_379_p2;
reg   [0:0] tmp_10_reg_578;
wire   [5:0] k_1_fu_398_p2;
reg   [5:0] k_1_reg_585;
reg    ap_sig_cseq_ST_st5_fsm_4;
reg    ap_sig_bdd_110;
wire   [11:0] next_mul_fu_404_p2;
reg   [11:0] next_mul_reg_590;
wire   [0:0] exitcond2_fu_392_p2;
wire   [0:0] tmp_14_fu_410_p2;
reg   [0:0] tmp_14_reg_595;
wire   [31:0] arrayA_q0;
reg  signed [31:0] arrayA_load_reg_609;
reg    ap_sig_cseq_ST_st6_fsm_5;
reg    ap_sig_bdd_138;
wire   [31:0] arrayB_q0;
reg  signed [31:0] arrayB_load_reg_614;
wire  signed [31:0] grp_fu_436_p2;
reg  signed [31:0] tmp_17_reg_619;
reg    ap_sig_cseq_ST_st12_fsm_11;
reg    ap_sig_bdd_149;
wire   [63:0] arrayC_q0;
reg   [63:0] arrayC_load_1_reg_624;
wire   [11:0] next_mul2_fu_449_p2;
reg   [11:0] next_mul2_reg_629;
reg    ap_sig_cseq_ST_st14_fsm_13;
reg    ap_sig_bdd_160;
wire   [5:0] i_3_fu_465_p2;
reg   [5:0] i_3_reg_637;
wire   [0:0] tmp_3_fu_471_p2;
reg   [0:0] tmp_3_reg_642;
wire   [0:0] exitcond1_fu_459_p2;
wire   [5:0] j_3_fu_490_p2;
reg   [5:0] j_3_reg_650;
reg    ap_sig_cseq_ST_st15_fsm_14;
reg    ap_sig_bdd_180;
wire   [0:0] tmp_12_fu_501_p2;
reg   [0:0] tmp_12_reg_655;
wire   [0:0] exitcond_fu_484_p2;
reg   [11:0] arrayA_address0;
reg    arrayA_ce0;
reg    arrayA_we0;
wire   [31:0] arrayA_d0;
reg   [11:0] arrayB_address0;
reg    arrayB_ce0;
reg    arrayB_we0;
wire   [31:0] arrayB_d0;
reg   [11:0] arrayC_address0;
reg    arrayC_ce0;
reg    arrayC_we0;
reg   [63:0] arrayC_d0;
wire    grp_MAT_Multiply_load_mat_fu_262_ap_start;
wire    grp_MAT_Multiply_load_mat_fu_262_ap_done;
wire    grp_MAT_Multiply_load_mat_fu_262_ap_idle;
wire    grp_MAT_Multiply_load_mat_fu_262_ap_ready;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_262_X_dout;
wire    grp_MAT_Multiply_load_mat_fu_262_X_empty_n;
wire    grp_MAT_Multiply_load_mat_fu_262_X_read;
wire   [11:0] grp_MAT_Multiply_load_mat_fu_262_arrayX_address0;
wire    grp_MAT_Multiply_load_mat_fu_262_arrayX_ce0;
wire    grp_MAT_Multiply_load_mat_fu_262_arrayX_we0;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_262_arrayX_d0;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_262_m;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_262_n;
wire    grp_MAT_Multiply_load_mat_fu_274_ap_start;
wire    grp_MAT_Multiply_load_mat_fu_274_ap_done;
wire    grp_MAT_Multiply_load_mat_fu_274_ap_idle;
wire    grp_MAT_Multiply_load_mat_fu_274_ap_ready;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_274_X_dout;
wire    grp_MAT_Multiply_load_mat_fu_274_X_empty_n;
wire    grp_MAT_Multiply_load_mat_fu_274_X_read;
wire   [11:0] grp_MAT_Multiply_load_mat_fu_274_arrayX_address0;
wire    grp_MAT_Multiply_load_mat_fu_274_arrayX_ce0;
wire    grp_MAT_Multiply_load_mat_fu_274_arrayX_we0;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_274_arrayX_d0;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_274_m;
wire   [31:0] grp_MAT_Multiply_load_mat_fu_274_n;
reg   [5:0] i_reg_171;
reg    ap_sig_cseq_ST_st2_fsm_1;
reg    ap_sig_bdd_256;
reg   [11:0] phi_mul1_reg_182;
reg   [5:0] j_reg_194;
reg   [5:0] k_reg_205;
reg    ap_sig_cseq_ST_st13_fsm_12;
reg    ap_sig_bdd_279;
reg   [11:0] phi_mul_reg_216;
reg   [5:0] i_1_reg_227;
reg   [11:0] phi_mul2_reg_238;
reg   [5:0] j_1_reg_250;
reg    ap_sig_cseq_ST_st16_fsm_15;
reg    ap_sig_bdd_298;
reg    ap_sig_bdd_304;
reg    grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg = 1'b0;
reg    grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg = 1'b0;
wire   [63:0] tmp_6_fu_369_p1;
wire   [63:0] tmp_15_fu_421_p1;
wire   [63:0] tmp_16_fu_431_p1;
wire   [63:0] tmp_13_fu_512_p1;
reg    ap_sig_cseq_ST_st11_fsm_10;
reg    ap_sig_bdd_329;
wire  signed [63:0] tmp_19_fu_443_p2;
wire   [0:0] tmp_7_fu_292_p2;
wire   [0:0] tmp_9_fu_298_p2;
wire   [0:0] tmp1_fu_304_p2;
wire   [0:0] tmp_fu_286_p2;
wire   [31:0] i_cast8_fu_322_p1;
wire   [11:0] p_addr_fu_363_p2;
wire   [31:0] j_cast7_fu_343_p1;
wire   [0:0] tmp_5_fu_374_p2;
wire   [31:0] k_cast6_fu_384_p1;
wire   [11:0] k_cast6_cast_fu_388_p1;
wire   [11:0] p_addr1_fu_415_p2;
wire   [11:0] p_addr4_fu_426_p2;
wire  signed [31:0] grp_fu_436_p0;
wire  signed [31:0] grp_fu_436_p1;
reg    ap_sig_cseq_ST_st7_fsm_6;
reg    ap_sig_bdd_411;
wire  signed [63:0] tmp_18_fu_440_p1;
wire   [31:0] i_1_cast4_fu_455_p1;
wire   [31:0] j_1_cast2_fu_476_p1;
wire   [0:0] tmp_11_fu_496_p2;
wire   [11:0] j_1_cast2_cast_fu_480_p1;
wire   [11:0] p_addr6_fu_506_p2;
wire    grp_fu_436_ce;
reg   [15:0] ap_NS_fsm;


MAT_Multiply_arrayA #(
    .DataWidth( 32 ),
    .AddressRange( 2500 ),
    .AddressWidth( 12 ))
arrayA_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( arrayA_address0 ),
    .ce0( arrayA_ce0 ),
    .we0( arrayA_we0 ),
    .d0( arrayA_d0 ),
    .q0( arrayA_q0 )
);

MAT_Multiply_arrayA #(
    .DataWidth( 32 ),
    .AddressRange( 2500 ),
    .AddressWidth( 12 ))
arrayB_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( arrayB_address0 ),
    .ce0( arrayB_ce0 ),
    .we0( arrayB_we0 ),
    .d0( arrayB_d0 ),
    .q0( arrayB_q0 )
);

MAT_Multiply_arrayC #(
    .DataWidth( 64 ),
    .AddressRange( 2500 ),
    .AddressWidth( 12 ))
arrayC_U(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .address0( arrayC_address0 ),
    .ce0( arrayC_ce0 ),
    .we0( arrayC_we0 ),
    .d0( arrayC_d0 ),
    .q0( arrayC_q0 )
);

MAT_Multiply_load_mat grp_MAT_Multiply_load_mat_fu_262(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_MAT_Multiply_load_mat_fu_262_ap_start ),
    .ap_done( grp_MAT_Multiply_load_mat_fu_262_ap_done ),
    .ap_idle( grp_MAT_Multiply_load_mat_fu_262_ap_idle ),
    .ap_ready( grp_MAT_Multiply_load_mat_fu_262_ap_ready ),
    .X_dout( grp_MAT_Multiply_load_mat_fu_262_X_dout ),
    .X_empty_n( grp_MAT_Multiply_load_mat_fu_262_X_empty_n ),
    .X_read( grp_MAT_Multiply_load_mat_fu_262_X_read ),
    .arrayX_address0( grp_MAT_Multiply_load_mat_fu_262_arrayX_address0 ),
    .arrayX_ce0( grp_MAT_Multiply_load_mat_fu_262_arrayX_ce0 ),
    .arrayX_we0( grp_MAT_Multiply_load_mat_fu_262_arrayX_we0 ),
    .arrayX_d0( grp_MAT_Multiply_load_mat_fu_262_arrayX_d0 ),
    .m( grp_MAT_Multiply_load_mat_fu_262_m ),
    .n( grp_MAT_Multiply_load_mat_fu_262_n )
);

MAT_Multiply_load_mat grp_MAT_Multiply_load_mat_fu_274(
    .ap_clk( ap_clk ),
    .ap_rst( ap_rst ),
    .ap_start( grp_MAT_Multiply_load_mat_fu_274_ap_start ),
    .ap_done( grp_MAT_Multiply_load_mat_fu_274_ap_done ),
    .ap_idle( grp_MAT_Multiply_load_mat_fu_274_ap_idle ),
    .ap_ready( grp_MAT_Multiply_load_mat_fu_274_ap_ready ),
    .X_dout( grp_MAT_Multiply_load_mat_fu_274_X_dout ),
    .X_empty_n( grp_MAT_Multiply_load_mat_fu_274_X_empty_n ),
    .X_read( grp_MAT_Multiply_load_mat_fu_274_X_read ),
    .arrayX_address0( grp_MAT_Multiply_load_mat_fu_274_arrayX_address0 ),
    .arrayX_ce0( grp_MAT_Multiply_load_mat_fu_274_arrayX_ce0 ),
    .arrayX_we0( grp_MAT_Multiply_load_mat_fu_274_arrayX_we0 ),
    .arrayX_d0( grp_MAT_Multiply_load_mat_fu_274_arrayX_d0 ),
    .m( grp_MAT_Multiply_load_mat_fu_274_m ),
    .n( grp_MAT_Multiply_load_mat_fu_274_n )
);

MAT_Multiply_mul_32s_32s_32_6 #(
    .ID( 1 ),
    .NUM_STAGE( 6 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
MAT_Multiply_mul_32s_32s_32_6_U5(
    .clk( ap_clk ),
    .reset( ap_rst ),
    .din0( grp_fu_436_p0 ),
    .din1( grp_fu_436_p1 ),
    .ce( grp_fu_436_ce ),
    .dout( grp_fu_436_p2 )
);



/// the current state (ap_CS_fsm) of the state machine. ///
always @ (posedge ap_clk)
begin : ap_ret_ap_CS_fsm
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_st1_fsm_0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

/// grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_310_p2 == ap_const_lv1_0))) begin
            grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_MAT_Multiply_load_mat_fu_262_ap_ready)) begin
            grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg assign process. ///
always @ (posedge ap_clk)
begin : ap_ret_grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg
    if (ap_rst == 1'b1) begin
        grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg <= ap_const_logic_0;
    end else begin
        if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_310_p2 == ap_const_lv1_0))) begin
            grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg <= ap_const_logic_1;
        end else if ((ap_const_logic_1 == grp_MAT_Multiply_load_mat_fu_274_ap_ready)) begin
            grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg <= ap_const_logic_0;
        end
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond4_fu_326_p2 == ap_const_lv1_0))) begin
        i_1_reg_227 <= ap_const_lv6_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~(ap_const_lv1_0 == exitcond_fu_484_p2))) begin
        i_1_reg_227 <= i_3_reg_637;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == exitcond3_fu_351_p2))) begin
        i_reg_171 <= i_2_reg_550;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_262_ap_done) | (ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_274_ap_done)))) begin
        i_reg_171 <= ap_const_lv6_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~ap_sig_bdd_304)) begin
        j_1_reg_250 <= j_3_reg_650;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ~(tmp_s_reg_538 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond1_fu_459_p2))) begin
        j_1_reg_250 <= ap_const_lv6_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & ~(ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
        j_reg_194 <= j_2_reg_568;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (exitcond4_fu_326_p2 == ap_const_lv1_0))) begin
        j_reg_194 <= ap_const_lv6_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        k_reg_205 <= k_1_reg_585;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_351_p2))) begin
        k_reg_205 <= ap_const_lv6_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & ~(ap_const_lv1_0 == exitcond3_fu_351_p2))) begin
        phi_mul1_reg_182 <= next_mul1_reg_542;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1) & ~((ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_262_ap_done) | (ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_274_ap_done)))) begin
        phi_mul1_reg_182 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & ~(exitcond4_fu_326_p2 == ap_const_lv1_0))) begin
        phi_mul2_reg_238 <= ap_const_lv12_0;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & ~(ap_const_lv1_0 == exitcond_fu_484_p2))) begin
        phi_mul2_reg_238 <= next_mul2_reg_629;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        phi_mul_reg_216 <= next_mul_reg_590;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_351_p2))) begin
        phi_mul_reg_216 <= ap_const_lv12_0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st6_fsm_5)) begin
        arrayA_load_reg_609 <= arrayA_q0;
        arrayB_load_reg_614 <= arrayB_q0;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_351_p2))) begin
        arrayC_addr_reg_573 <= tmp_6_fu_369_p1;
        tmp_10_reg_578 <= tmp_10_fu_379_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st12_fsm_11)) begin
        arrayC_load_1_reg_624 <= arrayC_q0;
        tmp_17_reg_619 <= grp_fu_436_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2)) begin
        i_2_reg_550 <= i_2_fu_332_p2;
        next_mul1_reg_542 <= next_mul1_fu_316_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ~(tmp_s_reg_538 == ap_const_lv1_0))) begin
        i_3_reg_637 <= i_3_fu_465_p2;
        next_mul2_reg_629 <= next_mul2_fu_449_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        j_2_reg_568 <= j_2_fu_357_p2;
        j_cast7_cast_reg_560[5 : 0] <= j_cast7_cast_fu_347_p1[5 : 0];
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        j_3_reg_650 <= j_3_fu_490_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        k_1_reg_585 <= k_1_fu_398_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == exitcond2_fu_392_p2))) begin
        next_mul_reg_590 <= next_mul_fu_404_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) & (ap_const_lv1_0 == exitcond_fu_484_p2))) begin
        tmp_12_reg_655 <= tmp_12_fu_501_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4) & (ap_const_lv1_0 == exitcond2_fu_392_p2) & ~(ap_const_lv1_0 == tmp_10_reg_578))) begin
        tmp_14_reg_595 <= tmp_14_fu_410_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st3_fsm_2) & (exitcond4_fu_326_p2 == ap_const_lv1_0))) begin
        tmp_2_reg_555 <= tmp_2_fu_338_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ~(tmp_s_reg_538 == ap_const_lv1_0) & (ap_const_lv1_0 == exitcond1_fu_459_p2))) begin
        tmp_3_reg_642 <= tmp_3_fu_471_p2;
    end
end

/// assign process. ///
always @(posedge ap_clk)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0) & ~(ap_start == ap_const_logic_0))) begin
        tmp_s_reg_538 <= tmp_s_fu_310_p2;
    end
end

/// A_read assign process. ///
always @ (grp_MAT_Multiply_load_mat_fu_262_X_read or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        A_read = grp_MAT_Multiply_load_mat_fu_262_X_read;
    end else begin
        A_read = ap_const_logic_0;
    end
end

/// B_read assign process. ///
always @ (grp_MAT_Multiply_load_mat_fu_274_X_read or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        B_read = grp_MAT_Multiply_load_mat_fu_274_X_read;
    end else begin
        B_read = ap_const_logic_0;
    end
end

/// C_write assign process. ///
always @ (tmp_12_reg_655 or ap_sig_cseq_ST_st16_fsm_15 or ap_sig_bdd_304)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st16_fsm_15) & ~(ap_const_lv1_0 == tmp_12_reg_655) & ~ap_sig_bdd_304)) begin
        C_write = ap_const_logic_1;
    end else begin
        C_write = ap_const_logic_0;
    end
end

/// ap_done assign process. ///
always @ (tmp_s_reg_538 or ap_sig_cseq_ST_st14_fsm_13 or exitcond1_fu_459_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ((tmp_s_reg_538 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond1_fu_459_p2)))) begin
        ap_done = ap_const_logic_1;
    end else begin
        ap_done = ap_const_logic_0;
    end
end

/// ap_idle assign process. ///
always @ (ap_start or ap_sig_cseq_ST_st1_fsm_0)
begin
    if ((~(ap_const_logic_1 == ap_start) & (ap_const_logic_1 == ap_sig_cseq_ST_st1_fsm_0))) begin
        ap_idle = ap_const_logic_1;
    end else begin
        ap_idle = ap_const_logic_0;
    end
end

/// ap_ready assign process. ///
always @ (tmp_s_reg_538 or ap_sig_cseq_ST_st14_fsm_13 or exitcond1_fu_459_p2)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st14_fsm_13) & ((tmp_s_reg_538 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond1_fu_459_p2)))) begin
        ap_ready = ap_const_logic_1;
    end else begin
        ap_ready = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st11_fsm_10 assign process. ///
always @ (ap_sig_bdd_329)
begin
    if (ap_sig_bdd_329) begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st11_fsm_10 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st12_fsm_11 assign process. ///
always @ (ap_sig_bdd_149)
begin
    if (ap_sig_bdd_149) begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st12_fsm_11 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st13_fsm_12 assign process. ///
always @ (ap_sig_bdd_279)
begin
    if (ap_sig_bdd_279) begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st13_fsm_12 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st14_fsm_13 assign process. ///
always @ (ap_sig_bdd_160)
begin
    if (ap_sig_bdd_160) begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st14_fsm_13 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st15_fsm_14 assign process. ///
always @ (ap_sig_bdd_180)
begin
    if (ap_sig_bdd_180) begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st15_fsm_14 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st16_fsm_15 assign process. ///
always @ (ap_sig_bdd_298)
begin
    if (ap_sig_bdd_298) begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st16_fsm_15 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st1_fsm_0 assign process. ///
always @ (ap_sig_bdd_32)
begin
    if (ap_sig_bdd_32) begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st1_fsm_0 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st2_fsm_1 assign process. ///
always @ (ap_sig_bdd_256)
begin
    if (ap_sig_bdd_256) begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st2_fsm_1 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st3_fsm_2 assign process. ///
always @ (ap_sig_bdd_75)
begin
    if (ap_sig_bdd_75) begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st3_fsm_2 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st4_fsm_3 assign process. ///
always @ (ap_sig_bdd_92)
begin
    if (ap_sig_bdd_92) begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st4_fsm_3 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st5_fsm_4 assign process. ///
always @ (ap_sig_bdd_110)
begin
    if (ap_sig_bdd_110) begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st5_fsm_4 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st6_fsm_5 assign process. ///
always @ (ap_sig_bdd_138)
begin
    if (ap_sig_bdd_138) begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st6_fsm_5 = ap_const_logic_0;
    end
end

/// ap_sig_cseq_ST_st7_fsm_6 assign process. ///
always @ (ap_sig_bdd_411)
begin
    if (ap_sig_bdd_411) begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_1;
    end else begin
        ap_sig_cseq_ST_st7_fsm_6 = ap_const_logic_0;
    end
end

/// arrayA_address0 assign process. ///
always @ (ap_sig_cseq_ST_st5_fsm_4 or grp_MAT_Multiply_load_mat_fu_262_arrayX_address0 or ap_sig_cseq_ST_st2_fsm_1 or tmp_15_fu_421_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        arrayA_address0 = tmp_15_fu_421_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayA_address0 = grp_MAT_Multiply_load_mat_fu_262_arrayX_address0;
    end else begin
        arrayA_address0 = 'bx;
    end
end

/// arrayA_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st5_fsm_4 or grp_MAT_Multiply_load_mat_fu_262_arrayX_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        arrayA_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayA_ce0 = grp_MAT_Multiply_load_mat_fu_262_arrayX_ce0;
    end else begin
        arrayA_ce0 = ap_const_logic_0;
    end
end

/// arrayA_we0 assign process. ///
always @ (grp_MAT_Multiply_load_mat_fu_262_arrayX_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayA_we0 = grp_MAT_Multiply_load_mat_fu_262_arrayX_we0;
    end else begin
        arrayA_we0 = ap_const_logic_0;
    end
end

/// arrayB_address0 assign process. ///
always @ (ap_sig_cseq_ST_st5_fsm_4 or grp_MAT_Multiply_load_mat_fu_274_arrayX_address0 or ap_sig_cseq_ST_st2_fsm_1 or tmp_16_fu_431_p1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        arrayB_address0 = tmp_16_fu_431_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayB_address0 = grp_MAT_Multiply_load_mat_fu_274_arrayX_address0;
    end else begin
        arrayB_address0 = 'bx;
    end
end

/// arrayB_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st5_fsm_4 or grp_MAT_Multiply_load_mat_fu_274_arrayX_ce0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st5_fsm_4)) begin
        arrayB_ce0 = ap_const_logic_1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayB_ce0 = grp_MAT_Multiply_load_mat_fu_274_arrayX_ce0;
    end else begin
        arrayB_ce0 = ap_const_logic_0;
    end
end

/// arrayB_we0 assign process. ///
always @ (grp_MAT_Multiply_load_mat_fu_274_arrayX_we0 or ap_sig_cseq_ST_st2_fsm_1)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st2_fsm_1)) begin
        arrayB_we0 = grp_MAT_Multiply_load_mat_fu_274_arrayX_we0;
    end else begin
        arrayB_we0 = ap_const_logic_0;
    end
end

/// arrayC_address0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or arrayC_addr_reg_573 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st13_fsm_12 or tmp_6_fu_369_p1 or tmp_13_fu_512_p1 or ap_sig_cseq_ST_st11_fsm_10)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        arrayC_address0 = tmp_6_fu_369_p1;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14)) begin
        arrayC_address0 = tmp_13_fu_512_p1;
    end else if (((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        arrayC_address0 = arrayC_addr_reg_573;
    end else begin
        arrayC_address0 = 'bx;
    end
end

/// arrayC_ce0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st15_fsm_14 or ap_sig_cseq_ST_st13_fsm_12 or ap_sig_cseq_ST_st11_fsm_10)
begin
    if (((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) | (ap_const_logic_1 == ap_sig_cseq_ST_st15_fsm_14) | (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) | (ap_const_logic_1 == ap_sig_cseq_ST_st11_fsm_10))) begin
        arrayC_ce0 = ap_const_logic_1;
    end else begin
        arrayC_ce0 = ap_const_logic_0;
    end
end

/// arrayC_d0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or ap_sig_cseq_ST_st13_fsm_12 or tmp_19_fu_443_p2)
begin
    if ((ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12)) begin
        arrayC_d0 = tmp_19_fu_443_p2;
    end else if ((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3)) begin
        arrayC_d0 = ap_const_lv64_0;
    end else begin
        arrayC_d0 = 'bx;
    end
end

/// arrayC_we0 assign process. ///
always @ (ap_sig_cseq_ST_st4_fsm_3 or exitcond3_fu_351_p2 or tmp_10_reg_578 or tmp_14_reg_595 or ap_sig_cseq_ST_st13_fsm_12)
begin
    if ((((ap_const_logic_1 == ap_sig_cseq_ST_st4_fsm_3) & (ap_const_lv1_0 == exitcond3_fu_351_p2)) | (~(ap_const_lv1_0 == tmp_10_reg_578) & (ap_const_logic_1 == ap_sig_cseq_ST_st13_fsm_12) & ~(ap_const_lv1_0 == tmp_14_reg_595)))) begin
        arrayC_we0 = ap_const_logic_1;
    end else begin
        arrayC_we0 = ap_const_logic_0;
    end
end
/// the next state (ap_NS_fsm) of the state machine. ///
always @ (ap_start or ap_CS_fsm or tmp_s_fu_310_p2 or tmp_s_reg_538 or exitcond4_fu_326_p2 or exitcond3_fu_351_p2 or tmp_10_reg_578 or exitcond2_fu_392_p2 or tmp_14_fu_410_p2 or exitcond1_fu_459_p2 or exitcond_fu_484_p2 or grp_MAT_Multiply_load_mat_fu_262_ap_done or grp_MAT_Multiply_load_mat_fu_274_ap_done or ap_sig_bdd_304)
begin
    case (ap_CS_fsm)
        ap_ST_st1_fsm_0 : 
        begin
            if ((~(ap_start == ap_const_logic_0) & (tmp_s_fu_310_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else if ((~(ap_start == ap_const_logic_0) & ~(tmp_s_fu_310_p2 == ap_const_lv1_0))) begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end else begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end
        end
        ap_ST_st2_fsm_1 : 
        begin
            if (~((ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_262_ap_done) | (ap_const_logic_0 == grp_MAT_Multiply_load_mat_fu_274_ap_done))) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st2_fsm_1;
            end
        end
        ap_ST_st3_fsm_2 : 
        begin
            if ((exitcond4_fu_326_p2 == ap_const_lv1_0)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end
        end
        ap_ST_st4_fsm_3 : 
        begin
            if (~(ap_const_lv1_0 == exitcond3_fu_351_p2)) begin
                ap_NS_fsm = ap_ST_st3_fsm_2;
            end else begin
                ap_NS_fsm = ap_ST_st5_fsm_4;
            end
        end
        ap_ST_st5_fsm_4 : 
        begin
            if (~(ap_const_lv1_0 == exitcond2_fu_392_p2)) begin
                ap_NS_fsm = ap_ST_st4_fsm_3;
            end else if (((ap_const_lv1_0 == exitcond2_fu_392_p2) & ~(ap_const_lv1_0 == tmp_10_reg_578) & ~(ap_const_lv1_0 == tmp_14_fu_410_p2))) begin
                ap_NS_fsm = ap_ST_st6_fsm_5;
            end else begin
                ap_NS_fsm = ap_ST_st13_fsm_12;
            end
        end
        ap_ST_st6_fsm_5 : 
        begin
            ap_NS_fsm = ap_ST_st7_fsm_6;
        end
        ap_ST_st7_fsm_6 : 
        begin
            ap_NS_fsm = ap_ST_st8_fsm_7;
        end
        ap_ST_st8_fsm_7 : 
        begin
            ap_NS_fsm = ap_ST_st9_fsm_8;
        end
        ap_ST_st9_fsm_8 : 
        begin
            ap_NS_fsm = ap_ST_st10_fsm_9;
        end
        ap_ST_st10_fsm_9 : 
        begin
            ap_NS_fsm = ap_ST_st11_fsm_10;
        end
        ap_ST_st11_fsm_10 : 
        begin
            ap_NS_fsm = ap_ST_st12_fsm_11;
        end
        ap_ST_st12_fsm_11 : 
        begin
            ap_NS_fsm = ap_ST_st13_fsm_12;
        end
        ap_ST_st13_fsm_12 : 
        begin
            ap_NS_fsm = ap_ST_st5_fsm_4;
        end
        ap_ST_st14_fsm_13 : 
        begin
            if (((tmp_s_reg_538 == ap_const_lv1_0) | ~(ap_const_lv1_0 == exitcond1_fu_459_p2))) begin
                ap_NS_fsm = ap_ST_st1_fsm_0;
            end else begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end
        end
        ap_ST_st15_fsm_14 : 
        begin
            if (~(ap_const_lv1_0 == exitcond_fu_484_p2)) begin
                ap_NS_fsm = ap_ST_st14_fsm_13;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        end
        ap_ST_st16_fsm_15 : 
        begin
            if (~ap_sig_bdd_304) begin
                ap_NS_fsm = ap_ST_st15_fsm_14;
            end else begin
                ap_NS_fsm = ap_ST_st16_fsm_15;
            end
        end
        default : 
        begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign C_din = arrayC_q0;

/// ap_sig_bdd_110 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_110 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_4]);
end

/// ap_sig_bdd_138 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_138 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_5]);
end

/// ap_sig_bdd_149 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_149 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_B]);
end

/// ap_sig_bdd_160 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_160 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_D]);
end

/// ap_sig_bdd_180 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_180 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_E]);
end

/// ap_sig_bdd_256 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_256 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_1]);
end

/// ap_sig_bdd_279 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_279 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_C]);
end

/// ap_sig_bdd_298 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_298 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_F]);
end

/// ap_sig_bdd_304 assign process. ///
always @ (C_full_n or tmp_12_reg_655)
begin
    ap_sig_bdd_304 = ((C_full_n == ap_const_logic_0) & ~(ap_const_lv1_0 == tmp_12_reg_655));
end

/// ap_sig_bdd_32 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_32 = (ap_CS_fsm[ap_const_lv32_0] == ap_const_lv1_1);
end

/// ap_sig_bdd_329 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_329 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_A]);
end

/// ap_sig_bdd_411 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_411 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_6]);
end

/// ap_sig_bdd_75 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_75 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_2]);
end

/// ap_sig_bdd_92 assign process. ///
always @ (ap_CS_fsm)
begin
    ap_sig_bdd_92 = (ap_const_lv1_1 == ap_CS_fsm[ap_const_lv32_3]);
end
assign arrayA_d0 = grp_MAT_Multiply_load_mat_fu_262_arrayX_d0;
assign arrayB_d0 = grp_MAT_Multiply_load_mat_fu_274_arrayX_d0;
assign exitcond1_fu_459_p2 = (i_1_reg_227 == ap_const_lv6_32? 1'b1: 1'b0);
assign exitcond2_fu_392_p2 = (k_reg_205 == ap_const_lv6_32? 1'b1: 1'b0);
assign exitcond3_fu_351_p2 = (j_reg_194 == ap_const_lv6_32? 1'b1: 1'b0);
assign exitcond4_fu_326_p2 = (i_reg_171 == ap_const_lv6_32? 1'b1: 1'b0);
assign exitcond_fu_484_p2 = (j_1_reg_250 == ap_const_lv6_32? 1'b1: 1'b0);
assign grp_MAT_Multiply_load_mat_fu_262_X_dout = A_dout;
assign grp_MAT_Multiply_load_mat_fu_262_X_empty_n = A_empty_n;
assign grp_MAT_Multiply_load_mat_fu_262_ap_start = grp_MAT_Multiply_load_mat_fu_262_ap_start_ap_start_reg;
assign grp_MAT_Multiply_load_mat_fu_262_m = mC;
assign grp_MAT_Multiply_load_mat_fu_262_n = mB;
assign grp_MAT_Multiply_load_mat_fu_274_X_dout = B_dout;
assign grp_MAT_Multiply_load_mat_fu_274_X_empty_n = B_empty_n;
assign grp_MAT_Multiply_load_mat_fu_274_ap_start = grp_MAT_Multiply_load_mat_fu_274_ap_start_ap_start_reg;
assign grp_MAT_Multiply_load_mat_fu_274_m = mB;
assign grp_MAT_Multiply_load_mat_fu_274_n = nC;
assign grp_fu_436_ce = ap_const_logic_1;
assign grp_fu_436_p0 = arrayB_load_reg_614;
assign grp_fu_436_p1 = arrayA_load_reg_609;
assign i_1_cast4_fu_455_p1 = i_1_reg_227;
assign i_2_fu_332_p2 = (i_reg_171 + ap_const_lv6_1);
assign i_3_fu_465_p2 = (i_1_reg_227 + ap_const_lv6_1);
assign i_cast8_fu_322_p1 = i_reg_171;
assign j_1_cast2_cast_fu_480_p1 = j_1_reg_250;
assign j_1_cast2_fu_476_p1 = j_1_reg_250;
assign j_2_fu_357_p2 = (j_reg_194 + ap_const_lv6_1);
assign j_3_fu_490_p2 = (j_1_reg_250 + ap_const_lv6_1);
assign j_cast7_cast_fu_347_p1 = j_reg_194;
assign j_cast7_fu_343_p1 = j_reg_194;
assign k_1_fu_398_p2 = (k_reg_205 + ap_const_lv6_1);
assign k_cast6_cast_fu_388_p1 = k_reg_205;
assign k_cast6_fu_384_p1 = k_reg_205;
assign next_mul1_fu_316_p2 = (phi_mul1_reg_182 + ap_const_lv12_32);
assign next_mul2_fu_449_p2 = (phi_mul2_reg_238 + ap_const_lv12_32);
assign next_mul_fu_404_p2 = (phi_mul_reg_216 + ap_const_lv12_32);
assign p_addr1_fu_415_p2 = (k_cast6_cast_fu_388_p1 + phi_mul1_reg_182);
assign p_addr4_fu_426_p2 = (j_cast7_cast_reg_560 + phi_mul_reg_216);
assign p_addr6_fu_506_p2 = (j_1_cast2_cast_fu_480_p1 + phi_mul2_reg_238);
assign p_addr_fu_363_p2 = (j_cast7_cast_fu_347_p1 + phi_mul1_reg_182);
assign tmp1_fu_304_p2 = (tmp_7_fu_292_p2 & tmp_9_fu_298_p2);
assign tmp_10_fu_379_p2 = (tmp_2_reg_555 & tmp_5_fu_374_p2);
assign tmp_11_fu_496_p2 = (j_1_cast2_fu_476_p1 < nC? 1'b1: 1'b0);
assign tmp_12_fu_501_p2 = (tmp_3_reg_642 & tmp_11_fu_496_p2);
assign tmp_13_fu_512_p1 = p_addr6_fu_506_p2;
assign tmp_14_fu_410_p2 = (k_cast6_fu_384_p1 < mB? 1'b1: 1'b0);
assign tmp_15_fu_421_p1 = p_addr1_fu_415_p2;
assign tmp_16_fu_431_p1 = p_addr4_fu_426_p2;
assign tmp_18_fu_440_p1 = tmp_17_reg_619;
assign tmp_19_fu_443_p2 = ($signed(arrayC_load_1_reg_624) + $signed(tmp_18_fu_440_p1));
assign tmp_2_fu_338_p2 = (i_cast8_fu_322_p1 < mC? 1'b1: 1'b0);
assign tmp_3_fu_471_p2 = (i_1_cast4_fu_455_p1 < mC? 1'b1: 1'b0);
assign tmp_5_fu_374_p2 = (j_cast7_fu_343_p1 < nC? 1'b1: 1'b0);
assign tmp_6_fu_369_p1 = p_addr_fu_363_p2;
assign tmp_7_fu_292_p2 = (mA == mC? 1'b1: 1'b0);
assign tmp_9_fu_298_p2 = (nB == nC? 1'b1: 1'b0);
assign tmp_fu_286_p2 = (nA == mB? 1'b1: 1'b0);
assign tmp_s_fu_310_p2 = (tmp1_fu_304_p2 & tmp_fu_286_p2);
always @ (posedge ap_clk)
begin
    j_cast7_cast_reg_560[11:6] <= 6'b000000;
end



endmodule //MAT_Multiply

