# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partA/partA.srcs/sources_1/bd/partA/ip/partA_auto_pc_0/partA_auto_pc_0.xci
# IP: The module: 'partA_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partA/partA.srcs/sources_1/bd/partA/ip/partA_auto_pc_0/partA_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partA_auto_pc_0'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst]

# IP: E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partA/partA.srcs/sources_1/bd/partA/ip/partA_auto_pc_0/partA_auto_pc_0.xci
# IP: The module: 'partA_auto_pc_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partA/partA.srcs/sources_1/bd/partA/ip/partA_auto_pc_0/partA_auto_pc_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'partA_auto_pc_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst]
