# 
# Synthesis run script generated by Vivado
# 

set_param xicom.use_bs_reader 1
debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.cache/wt [current_project]
set_property parent.project_path E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/partB.bd
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_processing_system7_0_0/partB_processing_system7_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_axi_dma_0_0/partB_axi_dma_0_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0_board.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_rst_processing_system7_0_100M_0/partB_rst_processing_system7_0_100M_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_xbar_0/partB_xbar_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0/partB_axis_data_fifo_0_0.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_pc_0/partB_auto_pc_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_pc_1/partB_auto_pc_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_0/partB_auto_us_0_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_0/partB_auto_us_0_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_1/partB_auto_us_1_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_1/partB_auto_us_1_clocks.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_2/partB_auto_us_2_ooc.xdc]
set_property used_in_implementation false [get_files -all e:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/ip/partB_auto_us_2/partB_auto_us_2_clocks.xdc]
set_property used_in_implementation false [get_files -all E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/partB_ooc.xdc]
set_property is_locked true [get_files E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/bd/partB/partB.bd]

read_verilog -library xil_defaultlib E:/Ubuntu_source_code_data/ECE_527_MP/mp2/partB/partB.srcs/sources_1/imports/hdl/partB_wrapper.v
read_xdc dont_touch.xdc
set_property used_in_implementation false [get_files dont_touch.xdc]
synth_design -top partB_wrapper -part xc7z020clg484-1
write_checkpoint -noxdef partB_wrapper.dcp
catch { report_utilization -file partB_wrapper_utilization_synth.rpt -pb partB_wrapper_utilization_synth.pb }
