webtalk_init -webtalk_dir E:\\Ubuntu_source_code_data\\ECE_527_MP\\mp2\\partC\\partC.sdk\\webtalk
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Wed Sep 23 23:09:28 2015" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "SDK v2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2015.1" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "amd64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211083026_1777510696_210611924_725" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "SDK" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "false" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "NA" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "gr96lv1n271cu6s4ev360b0ves" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "2015.1_10" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "10" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 7 , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "Service Pack 1  (build 7601)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-3630QM CPU @ 2.40GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2394 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "8.000 GB" -context "user_environment"
webtalk_register_client -client sdk
webtalk_add_data -client sdk -key uid -value "1443066468477" -context "sdk\\\\bsp/1443066468477"
webtalk_add_data -client sdk -key hwid -value "1443019499486" -context "sdk\\\\bsp/1443066468477"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\bsp/1443066468477"
webtalk_add_data -client sdk -key apptemplate -value "null" -context "sdk\\\\bsp/1443066468477"
webtalk_add_data -client sdk -key uid -value "1443066540796" -context "sdk\\\\application/1443066540796"
webtalk_add_data -client sdk -key hwid -value "1443019499486" -context "sdk\\\\application/1443066540796"
webtalk_add_data -client sdk -key bspid -value "1443066468477" -context "sdk\\\\application/1443066540796"
webtalk_add_data -client sdk -key newbsp -value "false" -context "sdk\\\\application/1443066540796"
webtalk_add_data -client sdk -key os -value "standalone" -context "sdk\\\\application/1443066540796"
webtalk_add_data -client sdk -key apptemplate -value "hello_world" -context "sdk\\\\application/1443066540796"
webtalk_transmit -clientid 3687701124 -regid "211083026_1777510696_210611924_725" -xml E:\\Ubuntu_source_code_data\\ECE_527_MP\\mp2\\partC\\partC.sdk\\webtalk\\usage_statistics_ext_sdk.xml -html E:\\Ubuntu_source_code_data\\ECE_527_MP\\mp2\\partC\\partC.sdk\\webtalk\\usage_statistics_ext_sdk.html -wdm E:\\Ubuntu_source_code_data\\ECE_527_MP\\mp2\\partC\\partC.sdk\\webtalk\\sdk_webtalk.wdm -intro "<H3>SDK Usage Report</H3><BR>"
webtalk_terminate
