// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and SystemC
// Version: 2015.1
// Copyright (C) 2015 Xilinx Inc. All rights reserved.
// 
// ===========================================================

#include "Accelerator_DOT_Multiply.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic Accelerator_DOT_Multiply::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<32> Accelerator_DOT_Multiply::ap_const_lv32_0 = "00000000000000000000000000000000";
const sc_logic Accelerator_DOT_Multiply::ap_const_logic_1 = sc_dt::Log_1;
const bool Accelerator_DOT_Multiply::ap_true = true;

Accelerator_DOT_Multiply::Accelerator_DOT_Multiply(sc_module_name name) : sc_module(name), mVcdFile(0) {
    Accelerator_DOT_Multiply_Loop_row_proc_U0 = new Accelerator_DOT_Multiply_Loop_row_proc("Accelerator_DOT_Multiply_Loop_row_proc_U0");
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_clk(ap_clk);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_rst(ap_rst);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_start(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_done(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_continue(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_idle(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_idle);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->ap_ready(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_ready);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->A_dout(Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->A_empty_n(Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->A_read(Accelerator_DOT_Multiply_Loop_row_proc_U0_A_read);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->C_din(Accelerator_DOT_Multiply_Loop_row_proc_U0_C_din);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->C_full_n(Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n);
    Accelerator_DOT_Multiply_Loop_row_proc_U0->C_write(Accelerator_DOT_Multiply_Loop_row_proc_U0_C_write);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_A_read);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_A_read );

    SC_METHOD(thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout);
    sensitive << ( A_dout );

    SC_METHOD(thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n);
    sensitive << ( A_empty_n );

    SC_METHOD(thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n);
    sensitive << ( C_full_n );

    SC_METHOD(thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue);
    sensitive << ( ap_sig_hs_continue );

    SC_METHOD(thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start);
    sensitive << ( ap_rst );
    sensitive << ( ap_start );

    SC_METHOD(thread_C_din);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_C_din );

    SC_METHOD(thread_C_write);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_C_write );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_sig_hs_done );

    SC_METHOD(thread_ap_idle);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_idle );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_sig_top_allready );

    SC_METHOD(thread_ap_sig_hs_continue);

    SC_METHOD(thread_ap_sig_hs_done);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done );

    SC_METHOD(thread_ap_sig_top_allready);
    sensitive << ( Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_ready );

    ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0 = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "Accelerator_DOT_Multiply_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT_HIER__
    sc_trace(mVcdFile, A_dout, "(port)A_dout");
    sc_trace(mVcdFile, A_empty_n, "(port)A_empty_n");
    sc_trace(mVcdFile, A_read, "(port)A_read");
    sc_trace(mVcdFile, C_din, "(port)C_din");
    sc_trace(mVcdFile, C_full_n, "(port)C_full_n");
    sc_trace(mVcdFile, C_write, "(port)C_write");
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start, "Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done, "Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue, "Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_idle, "Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_idle");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_ready, "Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_ready");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout, "Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n, "Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_A_read, "Accelerator_DOT_Multiply_Loop_row_proc_U0_A_read");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_C_din, "Accelerator_DOT_Multiply_Loop_row_proc_U0_C_din");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n, "Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n");
    sc_trace(mVcdFile, Accelerator_DOT_Multiply_Loop_row_proc_U0_C_write, "Accelerator_DOT_Multiply_Loop_row_proc_U0_C_write");
    sc_trace(mVcdFile, ap_sig_hs_continue, "ap_sig_hs_continue");
    sc_trace(mVcdFile, ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0, "ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0");
    sc_trace(mVcdFile, ap_sig_hs_done, "ap_sig_hs_done");
    sc_trace(mVcdFile, ap_CS, "ap_CS");
    sc_trace(mVcdFile, ap_sig_top_allready, "ap_sig_top_allready");
#endif

    }
}

Accelerator_DOT_Multiply::~Accelerator_DOT_Multiply() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    delete Accelerator_DOT_Multiply_Loop_row_proc_U0;
}

void Accelerator_DOT_Multiply::thread_ap_clk_no_reset_() {
    ap_CS = ap_const_logic_0;
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0 = ap_const_logic_0;
    } else {
        if (esl_seteq<1,1,1>(ap_const_logic_1, ap_sig_hs_done.read())) {
            ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done.read(), ap_const_logic_1)) {
            ap_reg_procdone_Accelerator_DOT_Multiply_Loop_row_proc_U0 = ap_const_logic_1;
        }
    }
}

void Accelerator_DOT_Multiply::thread_A_read() {
    A_read = Accelerator_DOT_Multiply_Loop_row_proc_U0_A_read.read();
}

void Accelerator_DOT_Multiply::thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout() {
    Accelerator_DOT_Multiply_Loop_row_proc_U0_A_dout = A_dout.read();
}

void Accelerator_DOT_Multiply::thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n() {
    Accelerator_DOT_Multiply_Loop_row_proc_U0_A_empty_n = A_empty_n.read();
}

void Accelerator_DOT_Multiply::thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n() {
    Accelerator_DOT_Multiply_Loop_row_proc_U0_C_full_n = C_full_n.read();
}

void Accelerator_DOT_Multiply::thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue() {
    Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_continue = ap_sig_hs_continue.read();
}

void Accelerator_DOT_Multiply::thread_Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start() {
    if ( ap_rst.read() == ap_const_logic_1) {
        Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start = ap_const_logic_0;
    } else {
        Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_start = ap_start.read();
    }
}

void Accelerator_DOT_Multiply::thread_C_din() {
    C_din = Accelerator_DOT_Multiply_Loop_row_proc_U0_C_din.read();
}

void Accelerator_DOT_Multiply::thread_C_write() {
    C_write = Accelerator_DOT_Multiply_Loop_row_proc_U0_C_write.read();
}

void Accelerator_DOT_Multiply::thread_ap_done() {
    ap_done = ap_sig_hs_done.read();
}

void Accelerator_DOT_Multiply::thread_ap_idle() {
    if (esl_seteq<1,1,1>(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_idle.read(), ap_const_logic_1)) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void Accelerator_DOT_Multiply::thread_ap_ready() {
    ap_ready = ap_sig_top_allready.read();
}

void Accelerator_DOT_Multiply::thread_ap_sig_hs_continue() {
    ap_sig_hs_continue = ap_const_logic_1;
}

void Accelerator_DOT_Multiply::thread_ap_sig_hs_done() {
    if (esl_seteq<1,1,1>(Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_done.read(), ap_const_logic_1)) {
        ap_sig_hs_done = ap_const_logic_1;
    } else {
        ap_sig_hs_done = ap_const_logic_0;
    }
}

void Accelerator_DOT_Multiply::thread_ap_sig_top_allready() {
    ap_sig_top_allready = Accelerator_DOT_Multiply_Loop_row_proc_U0_ap_ready.read();
}

}

