# 
# Synthesis run script generated by Vivado
# 

debug::add_scope template.lib 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
create_project -in_memory -part xc7z020clg484-1

set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.cache/wt [current_project]
set_property parent.project_path E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property board_part em.avnet.com:zed:part0:1.3 [current_project]
add_files E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/ip/charLib.coe
add_files -quiet E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.runs/charLib_synth_1/charLib.dcp
set_property used_in_implementation false [get_files E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.runs/charLib_synth_1/charLib.dcp]
read_verilog -library xil_defaultlib -sv E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/imports/PmodOLED_Source/OledEX.sv
read_verilog -library xil_defaultlib {
  E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/imports/PmodOLED_Source/SpiCtrl.v
  E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/imports/PmodOLED_Source/Delay.v
  E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/imports/PmodOLED_Source/OledInit.v
  E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/sources_1/imports/PmodOLED_Source/PmodOLEDCtrl.v
}
read_xdc E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/constrs_1/new/OLED_porting_2_constr.xdc
set_property used_in_implementation false [get_files E:/Ubuntu_source_code_data/ECE_527_MP/mp2/OLED_porting_2/OLED_porting_2.srcs/constrs_1/new/OLED_porting_2_constr.xdc]

synth_design -top PmodOLEDCtrl -part xc7z020clg484-1
write_checkpoint -noxdef PmodOLEDCtrl.dcp
catch { report_utilization -file PmodOLEDCtrl_utilization_synth.rpt -pb PmodOLEDCtrl_utilization_synth.pb }
